/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../src/components/AppLink/index.vue')['default']
    AppMain: typeof import('./../src/layout/components/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./../src/components/Breadcrumb/index.vue')['default']
    DashboardCard: typeof import('./../src/views/dashboard/components/DashboardCard.vue')['default']
    GFiltre: typeof import('./../src/components/GFiltre/index.vue')['default']
    GForm: typeof import('./../src/components/GForm/index.vue')['default']
    Hamburger: typeof import('./../src/components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./../src/components/HeaderSearch/index.vue')['default']
    IconSelect: typeof import('./../src/components/IconSelect/index.vue')['default']
    ImageUpload: typeof import('./../src/components/Upload/ImageUpload.vue')['default']
    LangSelect: typeof import('./../src/components/LangSelect/index.vue')['default']
    LayoutSelect: typeof import('./../src/layout/components/Settings/components/LayoutSelect.vue')['default']
    NavBar: typeof import('./../src/layout/components/NavBar/index.vue')['default']
    NavbarLeft: typeof import('./../src/layout/components/NavBar/components/NavbarLeft.vue')['default']
    NavbarRight: typeof import('./../src/layout/components/NavBar/components/NavbarRight.vue')['default']
    PageContent: typeof import('./../src/components/page-content/src/page-content.vue')['default']
    PageModal: typeof import('./../src/components/page-modal/src/page-modal.vue')['default']
    PageSearch: typeof import('./../src/components/page-search/src/page-search.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../src/layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./../src/layout/components/Sidebar/index.vue')['default']
    SidebarLogo: typeof import('./../src/layout/components/Sidebar/components/SidebarLogo.vue')['default']
    SidebarMenu: typeof import('./../src/layout/components/Sidebar/components/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./../src/layout/components/Sidebar/components/SidebarMenuItem.vue')['default']
    SidebarMenuItemTitle: typeof import('./../src/layout/components/Sidebar/components/SidebarMenuItemTitle.vue')['default']
    SidebarMixTopMenu: typeof import('./../src/layout/components/Sidebar/components/SidebarMixTopMenu.vue')['default']
    SidebarUser: typeof import('./../src/layout/components/Sidebar/components/SidebarUser.vue')['default']
    SizeSelect: typeof import('./../src/components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableCard: typeof import('./../src/views/dashboard/components/TableCard.vue')['default']
    TagsView: typeof import('./../src/layout/components/TagsView/index.vue')['default']
    ThemeColorPicker: typeof import('./../src/layout/components/Settings/components/ThemeColorPicker.vue')['default']
    UserImport: typeof import('./../src/views/backstage/users/components/user-import.vue')['default']
  }
}
